[package]
name = "test-composition-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.2", default-features = false, features = ["std"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }